#!/usr/bin/env bash
# End-to-end test with a private speech-dispatcher instance (its own socket,
# config and logs), the real client, the module config generated by install.sh,
# and the fake server (no model). The player is replaced by a silent one, and the
# user's own speech-dispatcher and configuration are not touched.
#
# Checks: an utterance completes; stopping mid-utterance keeps the module alive;
# and what happens when the server is down (the module gives up and
# speech-dispatcher falls back to espeak-ng). Skipped if speech-dispatcher or
# spd-say isn't installed.
#
# Needs the server's Python dependencies, like tests/run.sh provides:
#   uv run --with 'supertonic>=1.3.1' --with numpy bash tests/test_speechd.sh
set -uo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
command -v speech-dispatcher >/dev/null && command -v spd-say >/dev/null \
    || { echo "speech-dispatcher test: SKIPPED (speech-dispatcher/spd-say not installed)"; exit 0; }
PYTHON=${PYTHON:-python3}
# speech-dispatcher's modules open the sound server at startup even though our
# command plays the audio itself (silently here); point them at the real one.
PULSE_SOCKET=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/pulse/native
[ -S "$PULSE_SOCKET" ] \
    || { echo "speech-dispatcher test: SKIPPED (no PulseAudio/PipeWire socket at $PULSE_SOCKET)"; exit 0; }
export PULSE_SERVER=unix:$PULSE_SOCKET
# sd_generic before 0.12.0-rc3 (e.g. Ubuntu 24.04's 0.12.0~rc2) reports any
# non-killed command as finished, so a failed utterance doesn't make the module
# give up there (see docs/how-it-works.md).
# `speech-dispatcher -v` leaves out the rc suffix (Ubuntu's 0.12.0~rc2 prints
# "0.12.0"), so prefer the package version where there is one.
SD_VERSION_RAW=$(dpkg-query -W -f='${Version}' speech-dispatcher 2>/dev/null \
                 || rpm -q --qf '%{VERSION}' speech-dispatcher 2>/dev/null \
                 || speech-dispatcher -v 2>/dev/null)
SD_VERSION=$(printf '%s\n' "$SD_VERSION_RAW" | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?([~-]rc[0-9]+)?' | head -1)
echo "speech-dispatcher ${SD_VERSION:-(version unknown)} (from: ${SD_VERSION_RAW:-nothing})"
gives_up_on_failure() {
    case $SD_VERSION in
        "" | 0.12.0[~-]rc[3-9]*) return 0 ;;
        0.12.0[~-]rc*) return 1 ;;
    esac
    [ "$(printf '%s\n' 0.12 "$SD_VERSION" | sort -V | head -1)" = 0.12 ]
}

FAILS=0
PASSES=0
ok()   { PASSES=$((PASSES + 1)); }
fail() { FAILS=$((FAILS + 1)); printf '  FAIL: %s\n' "$*"; }
check() { if eval "$2"; then ok; else fail "$1"; fi; }

T=$(mktemp -d)
H=$T/home
mkdir -p "$H" "$T/bin" "$T/run" "$T/log"
chmod 700 "$T/run"
cleanup() {
    for pid in ${SD:-} ${SRV:-}; do kill "$pid" 2>/dev/null; wait "$pid" 2>/dev/null; done
    rm -rf "$T"
}
trap cleanup EXIT

# Generate the configuration with the real installer (stubbed systemctl etc.).
for cmd in systemctl pkill uv pw-play; do printf '#!/bin/sh\n' > "$T/bin/$cmd"; done
chmod +x "$T/bin/"*
env -i PATH="$T/bin:/usr/bin:/bin" HOME="$H" XDG_RUNTIME_DIR="$T/run" LANG=C \
    bash "$ROOT/install.sh" --languages en > "$T/install.out" 2>&1 \
    || { cat "$T/install.out"; echo "install.sh failed"; exit 1; }
CONFDIR=$H/.config/speech-dispatcher
LOG=$H/.cache/speechd_supertonic.log
SDLOG=$T/log/speech-dispatcher.log

start_server() {
    XDG_RUNTIME_DIR="$T/run" "$PYTHON" "$ROOT/tests/fake_server.py" --delay 0.3 2>>"$T/server.log" &
    SRV=$!
    for _ in $(seq 100); do [ -S "$T/run/supertonic-tts.sock" ] && return; sleep 0.1; done
    echo "fake server didn't start:"; cat "$T/server.log"; exit 1
}

# A player that takes a while, like real playback, then discards the audio. It is
# a single process (like pw-play), so killing it really stops it.
PLAYER_CODE="import sys, time; time.sleep(2.37); sys.stdin.buffer.read()"
export SUPERTONIC_PLAYER="python3 -c '$PLAYER_CODE'"
# Exact or anchored patterns, so pgrep can't match an unrelated command line
# (such as the shell that started this test).
CLIENT_PATTERN="^[^ ]*python3 $H/.local/share/speechd-supertonic/supertonic_say.py"
PLAYER_CMDLINE="python3 -c $PLAYER_CODE"
alive() { pgrep -f "$CLIENT_PATTERN" >/dev/null || pgrep -fx "$PLAYER_CMDLINE" >/dev/null; }
start_server
XDG_RUNTIME_DIR="$T/run" HOME="$H" speech-dispatcher -s -l 4 -c unix_socket -S "$T/sd.sock" \
    -C "$CONFDIR" -L "$T/log" -P "$T/sd.pid" -t 0 >/dev/null 2>&1 &
SD=$!
for _ in $(seq 100); do [ -S "$T/sd.sock" ] && break; sleep 0.1; done
[ -S "$T/sd.sock" ] || { echo "speech-dispatcher didn't start"; exit 1; }
export SPEECHD_ADDRESS="unix_socket:$T/sd.sock"

echo "all voices are registered"
VOICES=$(timeout 10 spd-say -o supertonic -L | awk 'NR > 1 {print $1}' | sort | tr '\n' ' ')
check "10 voices for en (got: $VOICES)" '[ "$VOICES" = "F1-en F2-en F3-en F4-en F5-en M1-en M2-en M3-en M4-en M5-en " ]'

echo "utterance completes"
timeout 20 spd-say -w -o supertonic -y F1-en "Hello from the test."; rc=$?
check "spd-say -w returns 0 (got $rc)" '[ $rc = 0 ]'
check "client logged playback finished" 'grep -q "playback finished" "$LOG"'
check "server got the request" 'grep -q "\[1\] start voice=F1 lang=en" "$T/server.log"'

echo "stopping mid-utterance ends it promptly and keeps the module alive"
# -w: wait for the utterance's end (or cancel) event, so its result can be checked.
timeout 20 spd-say -w -o supertonic -y F1-en "First sentence. Second sentence. Third sentence. Fourth sentence." &
SAY=$!
sleep 1
check "client and player are running before the stop" 'alive'
stop_at=$(date +%s%N)
timeout 5 spd-say -C
wait "$SAY"; rc=$?
stop_ms=$(( ($(date +%s%N) - stop_at) / 1000000 ))
echo "  (stopped utterance: spd-say -w exit $rc after ${stop_ms} ms)"
check "stopped utterance returns 0 (got $rc)" '[ $rc = 0 ]'
check "stopped utterance returns within 2s (took ${stop_ms} ms)" '[ $stop_ms -lt 2000 ]'
sleep 0.3
if alive; then
    fail "client and player are gone after the stop"
    pgrep -af "$CLIENT_PATTERN"; pgrep -afx "$PLAYER_CMDLINE"
    for i in 1 2 3 4 5 6 7 8 9 10; do sleep 0.5; alive || { echo "  (gone after $((i * 500)) ms more)"; break; }; done
else
    ok
fi
check "stop logged no playback finished for it" '[ "$(grep -c "playback finished" "$LOG")" = 1 ]'
timeout 20 spd-say -w -o supertonic -y F1-en "After the stop."; rc=$?
check "next utterance completes (got $rc)" '[ $rc = 0 ]'
check "module not restarted/crashed" '! grep -q "terminated abnormally" "$SDLOG"'
check "after-stop request reached our server" '[ "$(grep -c "start voice=" "$T/server.log")" -ge 3 ]'

if gives_up_on_failure; then
    echo "server down: module gives up, speech-dispatcher falls back"
    kill "$SRV"; wait "$SRV" 2>/dev/null; SRV=
    timeout 8 spd-say -w -o supertonic -y F1-en "Nobody is listening."; rc=$?
    check "client error in log" 'grep -q "can.t reach server" "$LOG"'
    # Which message depends on whether the module had fully exited when
    # speech-dispatcher noticed (output_check_module in its output.c).
    check "speech-dispatcher noticed the module died" \
        'grep -qE "terminated abnormally|Output module not running" "$SDLOG"'
    check "failed utterance gets no end event (spd-say -w times out; got $rc)" '[ $rc = 124 ]'
    if [ -x /usr/lib/speech-dispatcher-modules/sd_espeak-ng ] || command -v espeak-ng >/dev/null; then
        timeout 20 spd-say -w -o supertonic "Spoken by the fallback."; rc=$?
        check "next utterance completes via fallback (got $rc)" '[ $rc = 0 ]'
        check "fallback logged" 'grep -q "Couldn.t load default output module" "$SDLOG"'
    fi
else
    echo "server down: the failure is reported as a finished utterance (speech-dispatcher before 0.12.0-rc3)"
    kill "$SRV"; wait "$SRV" 2>/dev/null; SRV=
    timeout 8 spd-say -w -o supertonic -y F1-en "Nobody is listening."; rc=$?
    check "client error in log" 'grep -q "can.t reach server" "$LOG"'
    check "failed utterance still gets an end event (got $rc)" '[ $rc = 0 ]'
    check "module kept running" '! grep -qE "terminated abnormally|Output module not running" "$SDLOG"'
    check "no playback finished logged for it" '[ "$(grep -c "playback finished" "$LOG")" = 2 ]'
fi

echo
echo "speech-dispatcher tests: $PASSES passed, $FAILS failed"
[ "$FAILS" = 0 ]
